import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Header from "@/layout/header";
import Footer from "@/layout/footer";

import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Theme accentColor="blue" grayColor="gray">
          <Header />
          {children}
          <Footer />
        </Theme>
      </body>
    </html>
  );
}
